"""empty message

Revision ID: 7884e4f949f1
Revises: 45b8f690fbae
Create Date: 2025-08-12 23:00:17.846607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7884e4f949f1'
down_revision = '45b8f690fbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
