"""empty message

Revision ID: bc2966962643
Revises: 41ca724c19be
Create Date: 2025-08-12 19:37:52.128397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2966962643'
down_revision = '41ca724c19be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
