"""empty message

Revision ID: c4aac8863f12
Revises: bc2966962643
Create Date: 2025-08-12 22:53:05.744051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aac8863f12'
down_revision = 'bc2966962643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('leetcode_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hackerrank_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('hackerrank_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('leetcode_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('linkedin_url')

    # ### end Alembic commands ###
