"""empty message

Revision ID: f194954220b6
Revises: 0d25ec8c6ac3
Create Date: 2025-08-11 20:47:45.646642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f194954220b6'
down_revision = '0d25ec8c6ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('roles')
        batch_op.drop_column('failed_logins')
        batch_op.drop_column('lock_until')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('resumes_slug_key'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('resumes_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('failed_logins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('roles', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.create_table('token_blocklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blocklist_pkey'))
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###
